/* eslint-disable */
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /**
   * Represents non-fractional signed whole numeric values. Since the value may
   * exceed the size of a 32-bit integer, it's encoded as a string.
   */
  BigInt: { input: any; output: any; }
  /** An ISO 8601-encoded datetime */
  ISO8601DateTime: { input: any; output: any; }
};

/** Attributes for creating or updating an essence */
export type EssenceAttributes = {
  bitrate?: InputMaybe<Scalars['Int']['input']>;
  channels?: InputMaybe<Scalars['Int']['input']>;
  duration?: InputMaybe<Scalars['Float']['input']>;
  fps?: InputMaybe<Scalars['Int']['input']>;
  mimetype: Scalars['String']['input'];
  samplerate?: InputMaybe<Scalars['Int']['input']>;
  size: Scalars['BigInt']['input'];
};

/** Autogenerated input type of EssenceCreate */
export type EssenceCreateInput = {
  attributes: EssenceAttributes;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  collectionIdentifier: Scalars['String']['input'];
  filename: Scalars['String']['input'];
  itemIdentifier: Scalars['String']['input'];
};

/** Autogenerated input type of EssenceUpdate */
export type EssenceUpdateInput = {
  attributes: EssenceAttributes;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id: Scalars['ID']['input'];
};

/** Autogenerated input type of SetCollectionHasDepositForm */
export type SetCollectionHasDepositFormInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  identifier: Scalars['String']['input'];
};

export type GetCollectionQueryQueryVariables = Exact<{
  identifier: Scalars['ID']['input'];
}>;


export type GetCollectionQueryQuery = { __typename?: 'Query', collection?: { __typename?: 'Collection', identifier: string, title: string } | null };

export type SetCollectionHasDepositFormMutationVariables = Exact<{
  input: SetCollectionHasDepositFormInput;
}>;


export type SetCollectionHasDepositFormMutation = { __typename?: 'Mutation', setCollectionHasDepositForm?: { __typename?: 'SetCollectionHasDepositFormPayload', clientMutationId?: string | null } | null };

export type EssenceItemFragment = { __typename?: 'Essence', id: string, filename?: string | null, size?: any | null, mimetype?: string | null, channels?: number | null, citation?: string | null, duration?: number | null, fps?: number | null, bitrate?: number | null, samplerate?: number | null, createdAt?: any | null, updatedAt?: any | null } & { ' $fragmentName'?: 'EssenceItemFragment' };

export type GetEssenceQueryQueryVariables = Exact<{
  fullIdentifier: Scalars['ID']['input'];
  filename: Scalars['String']['input'];
}>;


export type GetEssenceQueryQuery = { __typename?: 'Query', essence?: { __typename?: 'Essence', id: string } | null };

export type EssenceCreateMutationMutationVariables = Exact<{
  input: EssenceCreateInput;
}>;


export type EssenceCreateMutationMutation = { __typename?: 'Mutation', essenceCreate?: { __typename?: 'EssenceCreatePayload', essence: (
      { __typename?: 'Essence' }
      & { ' $fragmentRefs'?: { 'EssenceItemFragment': EssenceItemFragment } }
    ) } | null };

export type EssenceUpdateMutationMutationVariables = Exact<{
  input: EssenceUpdateInput;
}>;


export type EssenceUpdateMutationMutation = { __typename?: 'Mutation', essenceUpdate?: { __typename?: 'EssenceUpdatePayload', essence: (
      { __typename?: 'Essence' }
      & { ' $fragmentRefs'?: { 'EssenceItemFragment': EssenceItemFragment } }
    ) } | null };

export type GetItemQueryQueryVariables = Exact<{
  fullIdentifier: Scalars['ID']['input'];
}>;


export type GetItemQueryQuery = { __typename?: 'Query', item?: { __typename?: 'Item', full_identifier: string, title?: string | null, metadata_exportable: boolean, created_at?: any | null, updated_at?: any | null } | null };

export type GetItemBwfCsvQueryQueryVariables = Exact<{
  fullIdentifier: Scalars['ID']['input'];
  filename: Scalars['String']['input'];
}>;


export type GetItemBwfCsvQueryQuery = { __typename?: 'Query', itemBwfCsv?: { __typename?: 'ItemBwfCsv', csv: string } | null };

export type GetItemId3QueryQueryVariables = Exact<{
  fullIdentifier: Scalars['ID']['input'];
}>;


export type GetItemId3QueryQuery = { __typename?: 'Query', itemId3?: { __typename?: 'ItemId3', txt: string } | null };

export type GetUserByUnikeyQueryQueryVariables = Exact<{
  unikey: Scalars['String']['input'];
}>;


export type GetUserByUnikeyQueryQuery = { __typename?: 'Query', userByUnikey?: { __typename?: 'EmailUser', email?: string | null, firstName?: string | null, lastName?: string | null } | null };

export const EssenceItemFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"EssenceItem"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Essence"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"filename"}},{"kind":"Field","name":{"kind":"Name","value":"size"}},{"kind":"Field","name":{"kind":"Name","value":"mimetype"}},{"kind":"Field","name":{"kind":"Name","value":"channels"}},{"kind":"Field","name":{"kind":"Name","value":"citation"}},{"kind":"Field","name":{"kind":"Name","value":"duration"}},{"kind":"Field","name":{"kind":"Name","value":"fps"}},{"kind":"Field","name":{"kind":"Name","value":"bitrate"}},{"kind":"Field","name":{"kind":"Name","value":"samplerate"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}}]}}]} as unknown as DocumentNode<EssenceItemFragment, unknown>;
export const GetCollectionQueryDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"GetCollectionQuery"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"identifier"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"collection"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"identifier"},"value":{"kind":"Variable","name":{"kind":"Name","value":"identifier"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"identifier"}},{"kind":"Field","name":{"kind":"Name","value":"title"}}]}}]}}]} as unknown as DocumentNode<GetCollectionQueryQuery, GetCollectionQueryQueryVariables>;
export const SetCollectionHasDepositFormDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"SetCollectionHasDepositForm"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"SetCollectionHasDepositFormInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"setCollectionHasDepositForm"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"clientMutationId"}}]}}]}}]} as unknown as DocumentNode<SetCollectionHasDepositFormMutation, SetCollectionHasDepositFormMutationVariables>;
export const GetEssenceQueryDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"GetEssenceQuery"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"fullIdentifier"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"filename"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"essence"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"fullIdentifier"},"value":{"kind":"Variable","name":{"kind":"Name","value":"fullIdentifier"}}},{"kind":"Argument","name":{"kind":"Name","value":"filename"},"value":{"kind":"Variable","name":{"kind":"Name","value":"filename"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}}]}}]}}]} as unknown as DocumentNode<GetEssenceQueryQuery, GetEssenceQueryQueryVariables>;
export const EssenceCreateMutationDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"EssenceCreateMutation"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"EssenceCreateInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"essenceCreate"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"essence"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"EssenceItem"}}]}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"EssenceItem"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Essence"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"filename"}},{"kind":"Field","name":{"kind":"Name","value":"size"}},{"kind":"Field","name":{"kind":"Name","value":"mimetype"}},{"kind":"Field","name":{"kind":"Name","value":"channels"}},{"kind":"Field","name":{"kind":"Name","value":"citation"}},{"kind":"Field","name":{"kind":"Name","value":"duration"}},{"kind":"Field","name":{"kind":"Name","value":"fps"}},{"kind":"Field","name":{"kind":"Name","value":"bitrate"}},{"kind":"Field","name":{"kind":"Name","value":"samplerate"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}}]}}]} as unknown as DocumentNode<EssenceCreateMutationMutation, EssenceCreateMutationMutationVariables>;
export const EssenceUpdateMutationDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"EssenceUpdateMutation"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"EssenceUpdateInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"essenceUpdate"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"essence"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"EssenceItem"}}]}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"EssenceItem"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Essence"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"filename"}},{"kind":"Field","name":{"kind":"Name","value":"size"}},{"kind":"Field","name":{"kind":"Name","value":"mimetype"}},{"kind":"Field","name":{"kind":"Name","value":"channels"}},{"kind":"Field","name":{"kind":"Name","value":"citation"}},{"kind":"Field","name":{"kind":"Name","value":"duration"}},{"kind":"Field","name":{"kind":"Name","value":"fps"}},{"kind":"Field","name":{"kind":"Name","value":"bitrate"}},{"kind":"Field","name":{"kind":"Name","value":"samplerate"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}}]}}]} as unknown as DocumentNode<EssenceUpdateMutationMutation, EssenceUpdateMutationMutationVariables>;
export const GetItemQueryDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"GetItemQuery"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"fullIdentifier"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"item"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"fullIdentifier"},"value":{"kind":"Variable","name":{"kind":"Name","value":"fullIdentifier"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"full_identifier"}},{"kind":"Field","name":{"kind":"Name","value":"title"}},{"kind":"Field","name":{"kind":"Name","value":"metadata_exportable"}},{"kind":"Field","name":{"kind":"Name","value":"created_at"}},{"kind":"Field","name":{"kind":"Name","value":"updated_at"}}]}}]}}]} as unknown as DocumentNode<GetItemQueryQuery, GetItemQueryQueryVariables>;
export const GetItemBwfCsvQueryDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"GetItemBwfCsvQuery"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"fullIdentifier"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"filename"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"itemBwfCsv"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"fullIdentifier"},"value":{"kind":"Variable","name":{"kind":"Name","value":"fullIdentifier"}}},{"kind":"Argument","name":{"kind":"Name","value":"filename"},"value":{"kind":"Variable","name":{"kind":"Name","value":"filename"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"csv"}}]}}]}}]} as unknown as DocumentNode<GetItemBwfCsvQueryQuery, GetItemBwfCsvQueryQueryVariables>;
export const GetItemId3QueryDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"GetItemId3Query"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"fullIdentifier"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"itemId3"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"fullIdentifier"},"value":{"kind":"Variable","name":{"kind":"Name","value":"fullIdentifier"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"txt"}}]}}]}}]} as unknown as DocumentNode<GetItemId3QueryQuery, GetItemId3QueryQueryVariables>;
export const GetUserByUnikeyQueryDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"GetUserByUnikeyQuery"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"unikey"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"userByUnikey"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"unikey"},"value":{"kind":"Variable","name":{"kind":"Name","value":"unikey"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"email"}},{"kind":"Field","name":{"kind":"Name","value":"firstName"}},{"kind":"Field","name":{"kind":"Name","value":"lastName"}}]}}]}}]} as unknown as DocumentNode<GetUserByUnikeyQueryQuery, GetUserByUnikeyQueryQueryVariables>;