/* eslint-disable */
/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
/** Attributes for creating or updating an essence */
export type EssenceAttributes = {
  bitrate?: unknown;
  channels?: number | null | undefined;
  duration?: number | null | undefined;
  extractedContent?: ExtractedContentInput | null | undefined;
  fps?: number | null | undefined;
  mimetype: string;
  samplerate?: number | null | undefined;
  size: unknown;
};

/** Autogenerated input type of EssenceCreate */
export type EssenceCreateInput = {
  attributes: EssenceAttributes;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: string | null | undefined;
  collectionIdentifier: string;
  filename: string;
  itemIdentifier: string;
  /** When called by an admin OAuth client (e.g. paragest), records the real uploader by their unikey. */
  uploaderUnikey?: string | null | undefined;
};

/** Autogenerated input type of EssenceUpdate */
export type EssenceUpdateInput = {
  attributes: EssenceAttributes;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: string | null | undefined;
  id: string | number;
};

/** Structured extracted content for an essence, typed by extractor semantics */
export type ExtractedContentInput = {
  contentType: ExtractedContentType;
  /** Required for PDF and ELAN content */
  segments?: Array<ExtractedSegmentInput> | null | undefined;
  /** Required for TEXT content */
  text?: string | null | undefined;
};

/** Which extractor semantics produced the extracted content */
export type ExtractedContentType =
  /** One segment per ELAN annotation */
  | 'ELAN'
  /** One segment per PDF page */
  | 'PDF'
  /** Flat plain text */
  | 'TEXT';

/** One location-addressed segment of extracted content */
export type ExtractedSegmentInput = {
  /** TIME_ALIGNED_ANNOTATION segments only */
  endMs?: number | null | undefined;
  /** PAGE segments only */
  page?: number | null | undefined;
  /** TIME_ALIGNED_ANNOTATION segments only */
  startMs?: number | null | undefined;
  text: string;
  /** TIME_ALIGNED_ANNOTATION segments only - the depositor's TIER_ID verbatim */
  tier?: string | null | undefined;
  type: SegmentType;
};

/** The kind of location a segment of extracted content is addressed by */
export type SegmentType =
  /** A PDF page */
  | 'PAGE'
  /** A time-aligned annotation, such as an ELAN annotation */
  | 'TIME_ALIGNED_ANNOTATION';

/** Autogenerated input type of SetCollectionHasDepositForm */
export type SetCollectionHasDepositFormInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: string | null | undefined;
  identifier: string;
};

export type GetCollectionQueryQueryVariables = Exact<{
  identifier: string | number;
}>;


export type GetCollectionQueryQuery = { collection: { identifier: string, title: string } | null };

export type SetCollectionHasDepositFormMutationVariables = Exact<{
  input: SetCollectionHasDepositFormInput;
}>;


export type SetCollectionHasDepositFormMutation = { setCollectionHasDepositForm: { clientMutationId: string | null } | null };

export type EssenceItemFragment = { id: string, filename: string | null, size: unknown, mimetype: string | null, channels: number | null, citation: string | null, duration: number | null, fps: number | null, bitrate: unknown, samplerate: number | null, createdAt: unknown, updatedAt: unknown } & { ' $fragmentName'?: 'EssenceItemFragment' };

export type GetEssenceQueryQueryVariables = Exact<{
  fullIdentifier: string | number;
  filename: string;
}>;


export type GetEssenceQueryQuery = { essence: { id: string } | null };

export type EssenceCreateMutationMutationVariables = Exact<{
  input: EssenceCreateInput;
}>;


export type EssenceCreateMutationMutation = { essenceCreate: { essence: { ' $fragmentRefs'?: { 'EssenceItemFragment': EssenceItemFragment } } } | null };

export type EssenceUpdateMutationMutationVariables = Exact<{
  input: EssenceUpdateInput;
}>;


export type EssenceUpdateMutationMutation = { essenceUpdate: { essence: { ' $fragmentRefs'?: { 'EssenceItemFragment': EssenceItemFragment } } } | null };

export type GetItemQueryQueryVariables = Exact<{
  fullIdentifier: string | number;
}>;


export type GetItemQueryQuery = { item: { full_identifier: string, title: string | null, metadata_exportable: boolean, created_at: unknown, updated_at: unknown } | null };

export type GetItemBwfCsvQueryQueryVariables = Exact<{
  fullIdentifier: string | number;
  filename: string;
}>;


export type GetItemBwfCsvQueryQuery = { itemBwfCsv: { csv: string } | null };

export type GetItemId3QueryQueryVariables = Exact<{
  fullIdentifier: string | number;
}>;


export type GetItemId3QueryQuery = { itemId3: { txt: string } | null };

export type GetUserByUnikeyQueryQueryVariables = Exact<{
  unikey: string;
}>;


export type GetUserByUnikeyQueryQuery = { userByUnikey: { email: string | null, firstName: string | null, lastName: string | null } | null };

export const EssenceItemFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"EssenceItem"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Essence"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"filename"}},{"kind":"Field","name":{"kind":"Name","value":"size"}},{"kind":"Field","name":{"kind":"Name","value":"mimetype"}},{"kind":"Field","name":{"kind":"Name","value":"channels"}},{"kind":"Field","name":{"kind":"Name","value":"citation"}},{"kind":"Field","name":{"kind":"Name","value":"duration"}},{"kind":"Field","name":{"kind":"Name","value":"fps"}},{"kind":"Field","name":{"kind":"Name","value":"bitrate"}},{"kind":"Field","name":{"kind":"Name","value":"samplerate"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}}]}}]} as unknown as DocumentNode<EssenceItemFragment, unknown>;
export const GetCollectionQueryDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"GetCollectionQuery"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"identifier"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"collection"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"identifier"},"value":{"kind":"Variable","name":{"kind":"Name","value":"identifier"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"identifier"}},{"kind":"Field","name":{"kind":"Name","value":"title"}}]}}]}}]} as unknown as DocumentNode<GetCollectionQueryQuery, GetCollectionQueryQueryVariables>;
export const SetCollectionHasDepositFormDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"SetCollectionHasDepositForm"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"SetCollectionHasDepositFormInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"setCollectionHasDepositForm"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"clientMutationId"}}]}}]}}]} as unknown as DocumentNode<SetCollectionHasDepositFormMutation, SetCollectionHasDepositFormMutationVariables>;
export const GetEssenceQueryDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"GetEssenceQuery"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"fullIdentifier"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"filename"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"essence"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"fullIdentifier"},"value":{"kind":"Variable","name":{"kind":"Name","value":"fullIdentifier"}}},{"kind":"Argument","name":{"kind":"Name","value":"filename"},"value":{"kind":"Variable","name":{"kind":"Name","value":"filename"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}}]}}]}}]} as unknown as DocumentNode<GetEssenceQueryQuery, GetEssenceQueryQueryVariables>;
export const EssenceCreateMutationDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"EssenceCreateMutation"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"EssenceCreateInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"essenceCreate"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"essence"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"EssenceItem"}}]}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"EssenceItem"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Essence"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"filename"}},{"kind":"Field","name":{"kind":"Name","value":"size"}},{"kind":"Field","name":{"kind":"Name","value":"mimetype"}},{"kind":"Field","name":{"kind":"Name","value":"channels"}},{"kind":"Field","name":{"kind":"Name","value":"citation"}},{"kind":"Field","name":{"kind":"Name","value":"duration"}},{"kind":"Field","name":{"kind":"Name","value":"fps"}},{"kind":"Field","name":{"kind":"Name","value":"bitrate"}},{"kind":"Field","name":{"kind":"Name","value":"samplerate"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}}]}}]} as unknown as DocumentNode<EssenceCreateMutationMutation, EssenceCreateMutationMutationVariables>;
export const EssenceUpdateMutationDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"EssenceUpdateMutation"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"EssenceUpdateInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"essenceUpdate"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"essence"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"EssenceItem"}}]}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"EssenceItem"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Essence"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"filename"}},{"kind":"Field","name":{"kind":"Name","value":"size"}},{"kind":"Field","name":{"kind":"Name","value":"mimetype"}},{"kind":"Field","name":{"kind":"Name","value":"channels"}},{"kind":"Field","name":{"kind":"Name","value":"citation"}},{"kind":"Field","name":{"kind":"Name","value":"duration"}},{"kind":"Field","name":{"kind":"Name","value":"fps"}},{"kind":"Field","name":{"kind":"Name","value":"bitrate"}},{"kind":"Field","name":{"kind":"Name","value":"samplerate"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}}]}}]} as unknown as DocumentNode<EssenceUpdateMutationMutation, EssenceUpdateMutationMutationVariables>;
export const GetItemQueryDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"GetItemQuery"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"fullIdentifier"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"item"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"fullIdentifier"},"value":{"kind":"Variable","name":{"kind":"Name","value":"fullIdentifier"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"full_identifier"}},{"kind":"Field","name":{"kind":"Name","value":"title"}},{"kind":"Field","name":{"kind":"Name","value":"metadata_exportable"}},{"kind":"Field","name":{"kind":"Name","value":"created_at"}},{"kind":"Field","name":{"kind":"Name","value":"updated_at"}}]}}]}}]} as unknown as DocumentNode<GetItemQueryQuery, GetItemQueryQueryVariables>;
export const GetItemBwfCsvQueryDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"GetItemBwfCsvQuery"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"fullIdentifier"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"filename"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"itemBwfCsv"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"fullIdentifier"},"value":{"kind":"Variable","name":{"kind":"Name","value":"fullIdentifier"}}},{"kind":"Argument","name":{"kind":"Name","value":"filename"},"value":{"kind":"Variable","name":{"kind":"Name","value":"filename"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"csv"}}]}}]}}]} as unknown as DocumentNode<GetItemBwfCsvQueryQuery, GetItemBwfCsvQueryQueryVariables>;
export const GetItemId3QueryDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"GetItemId3Query"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"fullIdentifier"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"itemId3"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"fullIdentifier"},"value":{"kind":"Variable","name":{"kind":"Name","value":"fullIdentifier"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"txt"}}]}}]}}]} as unknown as DocumentNode<GetItemId3QueryQuery, GetItemId3QueryQueryVariables>;
export const GetUserByUnikeyQueryDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"GetUserByUnikeyQuery"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"unikey"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"userByUnikey"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"unikey"},"value":{"kind":"Variable","name":{"kind":"Name","value":"unikey"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"email"}},{"kind":"Field","name":{"kind":"Name","value":"firstName"}},{"kind":"Field","name":{"kind":"Name","value":"lastName"}}]}}]}}]} as unknown as DocumentNode<GetUserByUnikeyQueryQuery, GetUserByUnikeyQueryQueryVariables>;